### ISSUE TITLE
i18n for Korean.

### ISSUE THREAD

**Issue by minyk** [whitdan/ArkhamHorrorLCGCampaignGuide#6]
Hi @whitdan 

I'm a board gamer in Korea and I love Arkham Horror LCG! I already run Korean translation of rules and scenarios(PDF format in release) on https://minyk.github.io/AHLCG-RULE-KO using markdown and `gitbook`. 

May I send PR for string translation for Korean ? I have a little bit experience on Android development until 2012, so I think I can do this.

Goob job and Thank you. 👍

**Comment by whitdan** [comment]
Hi! Really sorry I somehow missed this when you first posted it. I'm very happy to add any translations of the strings file which are provided to me.

**Comment by minyk** [comment]
Thanks. I will send PR soon. 😄
